package com.codesharp.cooper;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import com.codesharp.cooper.ChangeLog;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CHANGE_LOG.
*/
public class ChangeLogDao extends AbstractDao<ChangeLog, Long> {

    public static final String TABLENAME = "CHANGE_LOG";

    /**
     * Properties of entity ChangeLog.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AccountId = new Property(1, String.class, "accountId", false, "ACCOUNT_ID");
        public final static Property ChangeType = new Property(2, String.class, "changeType", false, "CHANGE_TYPE");
        public final static Property Dataid = new Property(3, String.class, "dataid", false, "DATAID");
        public final static Property IsSend = new Property(4, Boolean.class, "isSend", false, "IS_SEND");
        public final static Property Name = new Property(5, String.class, "name", false, "NAME");
        public final static Property TasklistId = new Property(6, String.class, "tasklistId", false, "TASKLIST_ID");
        public final static Property Value = new Property(7, String.class, "value", false, "VALUE");
    };


    public ChangeLogDao(DaoConfig config) {
        super(config);
    }
    
    public ChangeLogDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CHANGE_LOG' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'ACCOUNT_ID' TEXT," + // 1: accountId
                "'CHANGE_TYPE' TEXT," + // 2: changeType
                "'DATAID' TEXT," + // 3: dataid
                "'IS_SEND' INTEGER," + // 4: isSend
                "'NAME' TEXT," + // 5: name
                "'TASKLIST_ID' TEXT," + // 6: tasklistId
                "'VALUE' TEXT);"); // 7: value
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CHANGE_LOG'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ChangeLog entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String accountId = entity.getAccountId();
        if (accountId != null) {
            stmt.bindString(2, accountId);
        }
 
        String changeType = entity.getChangeType();
        if (changeType != null) {
            stmt.bindString(3, changeType);
        }
 
        String dataid = entity.getDataid();
        if (dataid != null) {
            stmt.bindString(4, dataid);
        }
 
        Boolean isSend = entity.getIsSend();
        if (isSend != null) {
            stmt.bindLong(5, isSend ? 1l: 0l);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(6, name);
        }
 
        String tasklistId = entity.getTasklistId();
        if (tasklistId != null) {
            stmt.bindString(7, tasklistId);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(8, value);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ChangeLog readEntity(Cursor cursor, int offset) {
        ChangeLog entity = new ChangeLog( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // accountId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // changeType
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // dataid
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // isSend
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // name
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // tasklistId
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // value
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ChangeLog entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAccountId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setChangeType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDataid(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setIsSend(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTasklistId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setValue(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ChangeLog entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ChangeLog entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
