package com.codesharp.cooper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHANGE_LOG.
 */
public class ChangeLog {

    private Long id;
    private String accountId;
    private String changeType;
    private String dataid;
    private Boolean isSend;
    private String name;
    private String tasklistId;
    private String value;

    public ChangeLog() {
    }

    public ChangeLog(Long id) {
        this.id = id;
    }

    public ChangeLog(Long id, String accountId, String changeType, String dataid, Boolean isSend, String name, String tasklistId, String value) {
        this.id = id;
        this.accountId = accountId;
        this.changeType = changeType;
        this.dataid = dataid;
        this.isSend = isSend;
        this.name = name;
        this.tasklistId = tasklistId;
        this.value = value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    public String getChangeType() {
        return changeType;
    }

    public void setChangeType(String changeType) {
        this.changeType = changeType;
    }

    public String getDataid() {
        return dataid;
    }

    public void setDataid(String dataid) {
        this.dataid = dataid;
    }

    public Boolean getIsSend() {
        return isSend;
    }

    public void setIsSend(Boolean isSend) {
        this.isSend = isSend;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTasklistId() {
        return tasklistId;
    }

    public void setTasklistId(String tasklistId) {
        this.tasklistId = tasklistId;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
