package com.codesharp.cooper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TASK.
 */
public class Task {

    private Long id;
    private String accountId;
    private String body;
    private java.util.Date createDate;
    private java.util.Date dueDate;
    private String taskId;
    private Boolean isPublic;
    private java.util.Date lastUpdateDate;
    private String priority;
    private Integer status;
    private Boolean editable;
    private String subject;
    private String tasklistId;

    public Task() {
    }

    public Task(Long id) {
        this.id = id;
    }

    public Task(Long id, String accountId, String body, java.util.Date createDate, java.util.Date dueDate, String taskId, Boolean isPublic, java.util.Date lastUpdateDate, String priority, Integer status, Boolean editable, String subject, String tasklistId) {
        this.id = id;
        this.accountId = accountId;
        this.body = body;
        this.createDate = createDate;
        this.dueDate = dueDate;
        this.taskId = taskId;
        this.isPublic = isPublic;
        this.lastUpdateDate = lastUpdateDate;
        this.priority = priority;
        this.status = status;
        this.editable = editable;
        this.subject = subject;
        this.tasklistId = tasklistId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public java.util.Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(java.util.Date createDate) {
        this.createDate = createDate;
    }

    public java.util.Date getDueDate() {
        return dueDate;
    }

    public void setDueDate(java.util.Date dueDate) {
        this.dueDate = dueDate;
    }

    public String getTaskId() {
        return taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    public Boolean getIsPublic() {
        return isPublic;
    }

    public void setIsPublic(Boolean isPublic) {
        this.isPublic = isPublic;
    }

    public java.util.Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    public void setLastUpdateDate(java.util.Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    public String getPriority() {
        return priority;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Boolean getEditable() {
        return editable;
    }

    public void setEditable(Boolean editable) {
        this.editable = editable;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getTasklistId() {
        return tasklistId;
    }

    public void setTasklistId(String tasklistId) {
        this.tasklistId = tasklistId;
    }

}
