package com.codesharp.cooper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TASKLIST.
 */
public class Tasklist {

    private Long id;
    private String accountId;
    private java.util.Date createTime;
    private Boolean editable;
    private String extensions;
    private String tasklistId;
    private String listType;
    private String name;

    public Tasklist() {
    }

    public Tasklist(Long id) {
        this.id = id;
    }

    public Tasklist(Long id, String accountId, java.util.Date createTime, Boolean editable, String extensions, String tasklistId, String listType, String name) {
        this.id = id;
        this.accountId = accountId;
        this.createTime = createTime;
        this.editable = editable;
        this.extensions = extensions;
        this.tasklistId = tasklistId;
        this.listType = listType;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    public java.util.Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    public Boolean getEditable() {
        return editable;
    }

    public void setEditable(Boolean editable) {
        this.editable = editable;
    }

    public String getExtensions() {
        return extensions;
    }

    public void setExtensions(String extensions) {
        this.extensions = extensions;
    }

    public String getTasklistId() {
        return tasklistId;
    }

    public void setTasklistId(String tasklistId) {
        this.tasklistId = tasklistId;
    }

    public String getListType() {
        return listType;
    }

    public void setListType(String listType) {
        this.listType = listType;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
