package com.codesharp.cooper;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.DaoConfig;
import de.greenrobot.dao.Property;

import com.codesharp.cooper.TaskIdx;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TASK_IDX.
*/
public class TaskIdxDao extends AbstractDao<TaskIdx, Long> {

    public static final String TABLENAME = "TASK_IDX";

    /**
     * Properties of entity TaskIdx.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property AccountId = new Property(1, String.class, "accountId", false, "ACCOUNT_ID");
        public final static Property By = new Property(2, String.class, "by", false, "BY");
        public final static Property Indexes = new Property(3, String.class, "indexes", false, "INDEXES");
        public final static Property Key = new Property(4, String.class, "key", false, "KEY");
        public final static Property Name = new Property(5, String.class, "name", false, "NAME");
        public final static Property TasklistId = new Property(6, String.class, "tasklistId", false, "TASKLIST_ID");
    };


    public TaskIdxDao(DaoConfig config) {
        super(config);
    }
    
    public TaskIdxDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'TASK_IDX' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'ACCOUNT_ID' TEXT," + // 1: accountId
                "'BY' TEXT," + // 2: by
                "'INDEXES' TEXT," + // 3: indexes
                "'KEY' TEXT," + // 4: key
                "'NAME' TEXT," + // 5: name
                "'TASKLIST_ID' TEXT);"); // 6: tasklistId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TASK_IDX'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TaskIdx entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String accountId = entity.getAccountId();
        if (accountId != null) {
            stmt.bindString(2, accountId);
        }
 
        String by = entity.getBy();
        if (by != null) {
            stmt.bindString(3, by);
        }
 
        String indexes = entity.getIndexes();
        if (indexes != null) {
            stmt.bindString(4, indexes);
        }
 
        String key = entity.getKey();
        if (key != null) {
            stmt.bindString(5, key);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(6, name);
        }
 
        String tasklistId = entity.getTasklistId();
        if (tasklistId != null) {
            stmt.bindString(7, tasklistId);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TaskIdx readEntity(Cursor cursor, int offset) {
        TaskIdx entity = new TaskIdx( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // accountId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // by
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // indexes
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // key
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // name
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // tasklistId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TaskIdx entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAccountId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBy(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIndexes(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setKey(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTasklistId(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TaskIdx entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TaskIdx entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
