package com.codesharp.cooper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TASK_IDX.
 */
public class TaskIdx {

    private Long id;
    private String accountId;
    private String by;
    private String indexes;
    private String key;
    private String name;
    private String tasklistId;

    public TaskIdx() {
    }

    public TaskIdx(Long id) {
        this.id = id;
    }

    public TaskIdx(Long id, String accountId, String by, String indexes, String key, String name, String tasklistId) {
        this.id = id;
        this.accountId = accountId;
        this.by = by;
        this.indexes = indexes;
        this.key = key;
        this.name = name;
        this.tasklistId = tasklistId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    public String getBy() {
        return by;
    }

    public void setBy(String by) {
        this.by = by;
    }

    public String getIndexes() {
        return indexes;
    }

    public void setIndexes(String indexes) {
        this.indexes = indexes;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getTasklistId() {
        return tasklistId;
    }

    public void setTasklistId(String tasklistId) {
        this.tasklistId = tasklistId;
    }

}
